export const STAKE_CONTRACT_ADDRESS=""; 
export const stNIBITOKEN_CONTRACT_ADDRESS = ""; 
export const VALIDATOR_REGISTARY_CONTRACT_ADDRESS = ""; 
export const REWARD_DISPATCHER_CONTRACT_ADDRESS = ""; 
